# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates: 
- package-ecosystem: npm
  directory: "/"
  pull-request-branch-name:
    separator: "/"
  schedule:
    interval: daily
    time: "10:00"
    timezone: Europe/Madrid
  labels:
  - "npm"
  - "dependencies"
  assignees:
  - macalbert
    
- package-ecosystem: nuget
  directories:
  - "/src/sdks/dotnet"
  - "/tests/sdks/dotnet"
  pull-request-branch-name:
    separator: "/"
  schedule:
    interval: daily
    time: "10:00"
    timezone: Europe/Madrid
  labels:
  - "nuget"
  - "dependencies"
  assignees:
  - macalbert

- package-ecosystem: gomod
  directories:
  - "/src/sdks/go"
  - "/tests/sdks/go"
  pull-request-branch-name:
    separator: "/"
  schedule:
    interval: daily
    time: "10:00"
    timezone: Europe/Madrid
  labels:
  - "go"
  - "dependencies"
  assignees:
  - macalbert

- package-ecosystem: maven
  directories:
  - "/src/sdks/java"
  - "/tests/sdks/java"
  pull-request-branch-name:
    separator: "/"
  schedule:
    interval: daily
    time: "10:00"
    timezone: Europe/Madrid
  labels:
  - "maven"
  - "dependencies"
  assignees:
  - macalbert

- package-ecosystem: pip
  directories:
  - "/src/sdks/python"
  - "/tests/sdks/python"
  pull-request-branch-name:
    separator: "/"
  schedule:
    interval: daily
    time: "10:00"
    timezone: Europe/Madrid
  labels:
  - "pip"
  - "dependencies"
  assignees:
  - macalbert

- package-ecosystem: npm
  directories:
  - "/src/sdks/nodejs"
  - "/tests/sdks/nodejs"
  pull-request-branch-name:
    separator: "/"
  schedule:
    interval: daily
    time: "10:00"
    timezone: Europe/Madrid
  labels:
  - "npm"
  - "dependencies"
  assignees:
  - macalbert

- package-ecosystem: github-actions
  directory: "/"
  pull-request-branch-name:
    separator: "/"
  schedule:
    interval: daily
    time: "10:00"
    timezone: Europe/Madrid
  labels:
  - "github-actions"
  - "dependencies"
  assignees:
  - macalbert