version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 24

    commands:
      - echo "Install started on `date`"
      - npm install -g aws-cdk
      - npm install -g pnpm

  pre_build:
    commands:
      - cd envilder
      - pnpm install --frozen-lockfile
      - pnpm --filter @envilder/website build

  build:
    commands:
      - echo "Build started on `date`"
      - cd src/iac
      - cdk deploy envilder-envilder-Website-production-stack --require-approval never

  post_build:
    commands:
      - echo "Build completed on `date`"

cache:
  paths:
    - "/root/.local/share/pnpm/store/**/*"
