name: 🧪 Node.js SDK Tests

permissions:
  id-token: write
  contents: read
  checks: write

on:
  workflow_dispatch:

  pull_request:
    branches:
      - '*'
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths:
      - '.github/workflows/tests-nodejs-sdk.yml'
      - 'src/sdks/nodejs/**'
      - 'tests/sdks/nodejs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  test-nodejs-sdk:
    runs-on: ubuntu-24.04
    if: ${{ !github.event.pull_request.draft }}
    timeout-minutes: 10
    env:
      LOCALSTACK_AUTH_TOKEN: ${{ secrets.LOCALSTACK_AUTH_TOKEN }}

    steps:
      - name: 🧱 Checkout repository
        uses: actions/checkout@v6

      - name: 📦 Install pnpm
        uses: pnpm/action-setup@v5
        with:
          version: 10

      - name: 🛠️ Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "20.x"
          cache: "pnpm"

      - name: 📦 Install dependencies
        run: pnpm install --frozen-lockfile

      - name: 🪙 Collect Coins (Configure AWS credentials)
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: 🌟 Format check
        run: npx biome check src/sdks/nodejs/src/ tests/sdks/nodejs/ && npx biome format src/sdks/nodejs/src/ tests/sdks/nodejs/

      - name: 🏗️ Build
        run: cd src/sdks/nodejs && pnpm build

      - name: 🍄 Run tests
        run: cd tests/sdks/nodejs && pnpm vitest run --reporter=verbose --reporter=junit --outputFile=${{ github.workspace }}/test-results.xml
        env:
          TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE: /var/run/docker.sock
          DOCKER_HOST: unix:///var/run/docker.sock

      - name: 📊 Test Results Reporter
        uses: dorny/test-reporter@v3
        if: always()
        with:
          name: Node.js SDK Test Results
          path: test-results.xml
          reporter: jest-junit
          only-summary: "false"
          list-suites: "all"
          list-tests: "all"
          max-annotations: "10"
          fail-on-error: "true"
