name: 🧪 .NET SDK Tests

on:
  workflow_dispatch:

  pull_request:
    branches:
      - '*'
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths:
      - '.github/workflows/tests-dotnet-sdk.yml'
      - 'src/sdks/dotnet/**'
      - 'tests/sdks/dotnet/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  test-dotnet-sdk:
    runs-on: ubuntu-24.04
    if: ${{ !github.event.pull_request.draft }}
    timeout-minutes: 10

    defaults:
      run:
        working-directory: src/sdks/dotnet

    steps:
      - name: 🧱 Checkout repository
        uses: actions/checkout@v6

      - name: 🛠️ Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.x'

      - name: 🪙 Collect Coins (Configure AWS credentials)
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: 🏗️ Build
        run: dotnet build Envilder.sln -c Release

      - name: 🌟 Format check
        run: dotnet format Envilder.sln --verify-no-changes --verbosity normal

      - name: 🍄 Run tests
        run: dotnet test ../../../tests/sdks/dotnet/ -c Release --no-build --verbosity normal